### ISSUE TITLE
Great plugin, does the job, but one request for user-roles please

### ISSUE THREAD

**Issue by mazazam** [stuartduff/WooCommerce-Dynamic-Pricing-Table#18] opened 2018-11-07 13:17 UTC
We're using the WPMU DEV - Members plugin, we've assigned trade pricing on certain products based on user role, but on an individual product basis.

My question is, can we display the table ONLY to certain user roles, i've managed to get it working using the following code: if( current_user_can('wholesale_buyer') || current_user_can('administrator') )

However when I place this on line 200 and a } on line 206. I get an error saying:
[07-Nov-2018 12:55:48 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/site/public_html/wp-content/plugins/woocommerce-dynamic-pricing-table-master/woocommerce-dynamic-pricing-table.php on line 207.

Is there some PHP misconfiguration I've done?

Please advise.

**Comment by stuartduff** [comment] 2020-02-19 20:22
I'm closing out this issue as it's a duplicate of #10

**Closed as completed by stuartduff** 2020-02-19 20:22 UTC
